name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Go
      uses: actions/setup-go@v5.0.0
      with:
        go-version: '1.21'

    - name: Gotestsum installer
      uses: autero1/action-gotestsum@v2.0.0
      with:
        gotestsum_version: '1.11.0'

    - name: Test
      run: make test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: ulyssessouza/envlang
